apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: brownbag
  name: brownbag
spec:
  replicas: 3
  selector:
    matchLabels:
      app: brownbag
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: brownbag
    spec:
      containers:
      - image: anurag0011/brownbagsession:12
        name: brownbag
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: brownbag
